version: "3.9"
services:
  db:
    image: mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - listy-data:/var/lib/mysql
    ports:
      - "3306:3306"

  service:
    image: listy-service
    environment:
      PORT: ${PORT}
      APP_URL: ${APP_URL}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  listy-data:
    driver: local
